name = "WaitProfileEstimators"
uuid = "396636b3-103e-4ec1-bf9c-f09d60477106"
authors = ["James Cannon <87723939+JamesMCannon@users.noreply.github.com>"]
version = "0.1.0"

[deps]
FaradayInternationalReferenceIonosphere = "13f5a3bc-1e41-4c76-a7e5-29a214aba9ea"

[compat]
FaradayInternationalReferenceIonosphere = "0.2.4"
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]